### PR TITLE
Add promote command

### PR DESCRIPTION
**Pull request by nolancon**

### CODE REVIEW

**Comment by Ricardo-Osorio** [comment]
This may not be the best cmd to port because the `move` may superseed it rendering it useless

When the `move` is run targeting `node-with-master` -> `node-with-replica` it tries a promotion automatically

**Comment by nolancon** [comment]
> This may not be the best cmd to port because the `move` may superseed it rendering it useless
> 
> When the `move` is run targeting `node-with-master` -> `node-with-replica` it tries a promotion automatically

Fair enough, I don't really know anything about the command. I just noticed it was missing. 
Is there a `move` command to be implemented?

**Comment by Mojachieee** [comment]
> > This may not be the best cmd to port because the `move` may superseed it rendering it useless
> > When the `move` is run targeting `node-with-master` -> `node-with-replica` it tries a promotion automatically
> 
> Fair enough, I don't really know anything about the command. I just noticed it was missing. Is there a `move` command to be implemented?

Move should exist under `storageos update volume move`

**Comment by nolancon** [comment]
> > > This may not be the best cmd to port because the `move` may superseed it rendering it useless
> > > When the `move` is run targeting `node-with-master` -> `node-with-replica` it tries a promotion automatically
> > 
> > 
> > Fair enough, I don't really know anything about the command. I just noticed it was missing. Is there a `move` command to be implemented?
> 
> Move should exist under `storageos update volume move`

Perfect, nothing to do then as it will fall under the `update` path.

**Pull request closed without merging**
